### PR TITLE
Implement shared state handling, menubar improvements

### PR DESCRIPTION
**Pull request by l-ouis**
menubar changes: selected breakdowns/years glow

shared state:
- react shared context in sharedContext.tsx
  - should contain all info for map region display (but not any specifics)
  - contains all menubar information

I was thinking it would be prettier for the three map components to use the shared context and then handle any specifics (like exit poll data) within the individual components

something like this would ideally allow map region + menubar state to persist between page switches. each component will have to parse the state however they see fit (for example:)
- menubar.tsx parses RaceType and Year into reactnodes (strings) 
- whereas the national map component may parse it to search the csv file

### CODE REVIEW

**Comment by l-ouis** [comment]
would appreciate a sanity check on the shared state stuff
the object might be a little too disorganized but otherwise it looks ok to me

**Comment by l-ouis** [comment]
Also would make solving conflicts with #103 a lot easier (can just remove the local sidebar stuff and instead use <Menubar />)

**Comment by arielshif** [comment]
this is a very structure-defining merge so this one is all yours @akslaym 

good stuff Louis

**Comment by akslaym** [comment]
The only downside I've ever seen to shared state is the occasional performance decrement if multiple of the shared state modules are being rendered at the same time and all are re-rendered with the change of one property, which will not be a big deal in our case given the way you are using it Louis. I think this is a great idea, will save tons of code and passing of hooks. Good work. I will approve and merge

**Review by akslaym — COMMENTED** [review]
Correction, I am getting an implementation error as the draw functionality is not working anymore. Will comment where I think the problem originates from.

**Comment by akslaym** [comment]
I have fixed the code so that the draw functionality works once again. The issue we are getting is you have not removed all of the local instances of each variable that is in the shared state. I fixed the drawing functionality, but do you think you could do one more sweep @l-ouis to grab the other leftover variables/hooks I might not have?

**Review by akslaym — APPROVED** [review]

**Pull request merged**
