### PR TITLE
Exit poll fixes

### PR DESCRIPTION
**Pull request by l-ouis**
@akslaym 

Needs a lot of testing imo

### CODE REVIEW

**Comment by l-ouis** [comment]
not entirely sure abt the styling maybe @arielshif can give feedback

**Comment by arielshif** [comment]
looks great but
- all of the text in the table is too big (1.2rem or so would be better, 2 rem is too much)
- when tables are big, they go over the edge of the page. not sure what a good solution is? maybe put the table in a container with height set to clamp, so you get the preferred padding above when available but move the table up as needed
- the demographic options on the sidebar require scrolling sometimes. this would be a large-ish fix, but everything in the sidebar can be a bit smaller, always (text 1.2 rem, icons maybe like 70% of their current size?)

**Comment by l-ouis** [comment]
@arielshif are you testing on the same dimensions as the display? I never had overflow issues

I'm assuming the 4K display will be at 200% scaling (so basically 1920x1080 in chrome)

**Comment by arielshif** [comment]
oh good point, I was testing on my computer natively

**Pull request merged**
